### ISSUE TITLE
read.abort is not a function

### ISSUE THREAD

**Issue by dominictarr** [pull-stream/pull-handshake#2]
time to stop ignoring this one.
https://github.com/ssbc/scuttlebot/pull/326#issuecomment-205132241

plan: stare at the code and try and guess how it could happen.
try writing tests that exercise state transitions I haven't thought about.

**Comment by bcomnes** [comment]
~~https://github.com/dominictarr/pull-reader/blob/master/index.js#L86-L87 looks fishy.~~ nm

**Comment by dominictarr** [comment]
closing, see https://github.com/dominictarr/pull-reader/issues/1
